server:
  port: 7050
  servlet:
    context-path: /coupon-settlement
spring:
  application:
    name: eureka-client-coupon-settlement
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

logging:
  level:
    org.sllxgmm.coupon: debug